# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bcp47_spec` gem.
# Please instead update this file by running `bin/tapioca gem bcp47_spec`.

module BCP47
  class << self
    # @raise [InvalidLanguageTag]
    def parse(language_tag); end

    # @return [Boolean]
    def valid?(language_tag); end
  end
end

class BCP47::InvalidLanguageTag < ::StandardError; end

module BCP47::Parser
  class << self
    def parse(language_tag); end

    private

    def named_captures(match); end
    def split_extensions(extensions); end
  end
end

# Simplified check. Not implementing high level privateuse / grandfathered.
# Should replace with a proper check at some point.
BCP47::Parser::ALPHANUM = T.let(T.unsafe(nil), Regexp)

BCP47::Parser::EXTENSION = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::EXTLANG = T.let(T.unsafe(nil), Regexp)

# Ruby .match only keeps the first captured group, so expressions like variants/extensions we need to keep everything
# in one captured group, then break them down in multipe groups separately
BCP47::Parser::LANGTAG = T.let(T.unsafe(nil), Regexp)

BCP47::Parser::LANGUAGE = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::LANGUAGE_TAG = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::PRIVATEUSE = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::REGION = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::SCRIPT = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::SINGLETON = T.let(T.unsafe(nil), Regexp)
BCP47::Parser::VARIANT = T.let(T.unsafe(nil), Regexp)

class BCP47::Tag < ::Struct
  # Returns the value of attribute extensions
  #
  # @return [Object] the current value of extensions
  def extensions; end

  # Sets the attribute extensions
  #
  # @param value [Object] the value to set the attribute extensions to.
  # @return [Object] the newly set value
  def extensions=(_); end

  # Returns the value of attribute language
  #
  # @return [Object] the current value of language
  def language; end

  # Sets the attribute language
  #
  # @param value [Object] the value to set the attribute language to.
  # @return [Object] the newly set value
  def language=(_); end

  # Returns the value of attribute private
  #
  # @return [Object] the current value of private
  def private; end

  # Sets the attribute private
  #
  # @param value [Object] the value to set the attribute private to.
  # @return [Object] the newly set value
  def private=(_); end

  # Returns the value of attribute region
  #
  # @return [Object] the current value of region
  def region; end

  # Sets the attribute region
  #
  # @param value [Object] the value to set the attribute region to.
  # @return [Object] the newly set value
  def region=(_); end

  # Returns the value of attribute script
  #
  # @return [Object] the current value of script
  def script; end

  # Sets the attribute script
  #
  # @param value [Object] the value to set the attribute script to.
  # @return [Object] the newly set value
  def script=(_); end

  # Returns the value of attribute variants
  #
  # @return [Object] the current value of variants
  def variants; end

  # Sets the attribute variants
  #
  # @param value [Object] the value to set the attribute variants to.
  # @return [Object] the newly set value
  def variants=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

BCP47::VERSION = T.let(T.unsafe(nil), String)
