# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `binding_of_caller` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module BindingOfCaller
end

module BindingOfCaller::BindingExtensions
  def callers; end
  def frame_count; end
  def frame_description; end
  def frame_type; end
  def of_caller(n); end
end

BindingOfCaller::VERSION = T.let(T.unsafe(nil), String)
