# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dotenv-rails` gem.
# Please instead update this file by running `bin/tapioca gem dotenv-rails`.

# The top level Dotenv module. The entrypoint for the application logic.
module Dotenv
  private

  def ignoring_nonexistent_files; end
  def instrument(name, payload = T.unsafe(nil), &block); end
  def load(*filenames); end

  # same as `load`, but raises Errno::ENOENT if any files don't exist
  def load!(*filenames); end

  # same as `load`, but will override existing values in `ENV`
  def overload(*filenames); end

  # same as `overload`, but raises Errno::ENOENT if any files don't exist
  def overload!(*filenames); end

  # returns a hash of parsed key/value pairs but does not modify ENV
  def parse(*filenames); end

  def require_keys(*keys); end

  # Internal: Helper to expand list of filenames.
  #
  # Returns a hash of all the loaded environment variables.
  def with(*filenames); end

  class << self
    def ignoring_nonexistent_files; end
    def instrument(name, payload = T.unsafe(nil), &block); end

    # Returns the value of attribute instrumenter.
    def instrumenter; end

    # Sets the attribute instrumenter
    #
    # @param value the value to set the attribute instrumenter to.
    def instrumenter=(_arg0); end

    def load(*filenames); end

    # same as `load`, but raises Errno::ENOENT if any files don't exist
    def load!(*filenames); end

    # same as `load`, but will override existing values in `ENV`
    def overload(*filenames); end

    # same as `overload`, but raises Errno::ENOENT if any files don't exist
    def overload!(*filenames); end

    # returns a hash of parsed key/value pairs but does not modify ENV
    def parse(*filenames); end

    # @raise [MissingKeys]
    def require_keys(*keys); end

    # Internal: Helper to expand list of filenames.
    #
    # Returns a hash of all the loaded environment variables.
    def with(*filenames); end
  end
end

# Dotenv Railtie for using Dotenv to load environment from a file into
# Rails applications
class Dotenv::Railtie < ::Rails::Railtie
  # Public: Load dotenv
  #
  # This will get called during the `before_configuration` callback, but you
  # can manually call `Dotenv::Railtie.load` if you needed it sooner.
  def load; end

  # Public: Reload dotenv
  #
  # Same as `load`, but will override existing values in `ENV`
  def overload; end

  # Internal: `Rails.root` is nil in Rails 4.1 before the application is
  # initialized, so this falls back to the `RAILS_ROOT` environment variable,
  # or the current working directory.
  def root; end

  private

  def dotenv_files; end

  class << self
    # Rails uses `#method_missing` to delegate all class methods to the
    # instance, which means `Kernel#load` gets called here. We don't want that.
    def load; end
  end
end
