# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `orm_adapter` gem.
# Please instead update this file by running `tapioca sync`.

# typed: strict

module OrmAdapter
  class << self
    def adapters; end
  end
end

class OrmAdapter::ActiveRecord < ::OrmAdapter::Base
  def column_names; end
  def create!(attributes = T.unsafe(nil)); end
  def destroy(object); end
  def find_all(options = T.unsafe(nil)); end
  def find_first(options = T.unsafe(nil)); end
  def get(id); end
  def get!(id); end

  protected

  def conditions_to_fields(conditions); end
  def construct_relation(relation, options); end
  def order_clause(order); end
end

class OrmAdapter::Base
  def initialize(klass); end

  def column_names; end
  def create!(attributes = T.unsafe(nil)); end
  def destroy(object); end
  def find_all(options = T.unsafe(nil)); end
  def find_first(options = T.unsafe(nil)); end
  def get(id); end
  def get!(id); end
  def klass; end

  protected

  def extract_conditions!(options = T.unsafe(nil)); end
  def normalize_order(order); end
  def valid_object?(object); end
  def wrap_key(key); end

  class << self
    def inherited(adapter); end
  end
end

class OrmAdapter::NotSupportedError < ::NotImplementedError
  def to_s; end
end

module OrmAdapter::ToAdapter
  def to_adapter; end
end

OrmAdapter::VERSION = T.let(T.unsafe(nil), String)
