# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-cors` gem.
# Please instead update this file by running `tapioca sync`.

# typed: true

module Rack
  class << self
    def release; end
    def version; end
  end
end

Rack::CACHE_CONTROL = T.let(T.unsafe(nil), String)

Rack::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

Rack::CONTENT_TYPE = T.let(T.unsafe(nil), String)

class Rack::Cors
  def initialize(app, opts = T.unsafe(nil), &block); end

  def allow(&block); end
  def call(env); end
  def debug?; end

  protected

  def all_resources; end
  def debug(env, message = T.unsafe(nil), &block); end
  def evaluate_path(env); end
  def match_resource(path, env); end
  def process_cors(env, path); end
  def process_preflight(env, path); end
  def resource_for_path(path_info); end
  def select_logger(env); end
end

Rack::Cors::CORS_SIMPLE_HEADERS = T.let(T.unsafe(nil), Array)

Rack::Cors::DEFAULT_VARY_HEADERS = T.let(T.unsafe(nil), Array)

Rack::Cors::ENV_KEY = T.let(T.unsafe(nil), String)

Rack::Cors::HTTP_ACCESS_CONTROL_REQUEST_HEADERS = T.let(T.unsafe(nil), String)

Rack::Cors::HTTP_ACCESS_CONTROL_REQUEST_METHOD = T.let(T.unsafe(nil), String)

Rack::Cors::HTTP_ORIGIN = T.let(T.unsafe(nil), String)

Rack::Cors::HTTP_X_ORIGIN = T.let(T.unsafe(nil), String)

Rack::Cors::OPTIONS = T.let(T.unsafe(nil), String)

Rack::Cors::PATH_INFO = T.let(T.unsafe(nil), String)

Rack::Cors::RACK_CORS = T.let(T.unsafe(nil), String)

Rack::Cors::RACK_LOGGER = T.let(T.unsafe(nil), String)

Rack::Cors::REQUEST_METHOD = T.let(T.unsafe(nil), String)

class Rack::Cors::Resource
  def initialize(public_resource, path, opts = T.unsafe(nil)); end

  def credentials; end
  def credentials=(_arg0); end
  def expose; end
  def expose=(_arg0); end
  def headers; end
  def headers=(_arg0); end
  def if_proc; end
  def if_proc=(_arg0); end
  def match?(path, env); end
  def matches_path?(path); end
  def max_age; end
  def max_age=(_arg0); end
  def methods; end
  def methods=(_arg0); end
  def path; end
  def path=(_arg0); end
  def pattern; end
  def pattern=(_arg0); end
  def process_preflight(env, result); end
  def to_headers(env); end
  def vary_headers; end
  def vary_headers=(_arg0); end

  protected

  def allow_headers?(request_headers); end
  def compile(path); end
  def ensure_enum(v); end
  def origin_for_response_header(origin); end
  def public_resource?; end
  def to_preflight_headers(env); end
end

class Rack::Cors::Resource::CorsMisconfigurationError < ::StandardError
  def message; end
end

class Rack::Cors::Resources
  def initialize; end

  def allow_origin?(source, env = T.unsafe(nil)); end
  def match_resource(path, env); end
  def origins(*args, &blk); end
  def public_resources?; end
  def resource(path, opts = T.unsafe(nil)); end
  def resource_for_path(path); end
  def resources; end
end

class Rack::Cors::Result
  def append_header(headers); end
  def hit; end
  def hit=(_arg0); end
  def hit?; end
  def miss(reason); end
  def miss_reason; end
  def miss_reason=(_arg0); end
  def preflight; end
  def preflight=(_arg0); end
  def preflight?; end

  class << self
    def hit(env); end
    def miss(env, reason); end
    def preflight(env); end
  end
end

Rack::Cors::Result::HEADER_KEY = T.let(T.unsafe(nil), String)

Rack::Cors::Result::MISS_DENY_HEADER = T.let(T.unsafe(nil), String)

Rack::Cors::Result::MISS_DENY_METHOD = T.let(T.unsafe(nil), String)

Rack::Cors::Result::MISS_NO_METHOD = T.let(T.unsafe(nil), String)

Rack::Cors::Result::MISS_NO_ORIGIN = T.let(T.unsafe(nil), String)

Rack::Cors::Result::MISS_NO_PATH = T.let(T.unsafe(nil), String)

Rack::Cors::VARY = T.let(T.unsafe(nil), String)

Rack::DELETE = T.let(T.unsafe(nil), String)

Rack::ETAG = T.let(T.unsafe(nil), String)

Rack::EXPIRES = T.let(T.unsafe(nil), String)

Rack::File = Rack::Files

Rack::GET = T.let(T.unsafe(nil), String)

Rack::HEAD = T.let(T.unsafe(nil), String)

Rack::HTTPS = T.let(T.unsafe(nil), String)

Rack::HTTP_COOKIE = T.let(T.unsafe(nil), String)

Rack::HTTP_HOST = T.let(T.unsafe(nil), String)

Rack::HTTP_PORT = T.let(T.unsafe(nil), String)

Rack::HTTP_VERSION = T.let(T.unsafe(nil), String)

Rack::LINK = T.let(T.unsafe(nil), String)

Rack::OPTIONS = T.let(T.unsafe(nil), String)

Rack::PATCH = T.let(T.unsafe(nil), String)

Rack::PATH_INFO = T.let(T.unsafe(nil), String)

Rack::POST = T.let(T.unsafe(nil), String)

Rack::PUT = T.let(T.unsafe(nil), String)

Rack::QUERY_STRING = T.let(T.unsafe(nil), String)

Rack::RACK_ERRORS = T.let(T.unsafe(nil), String)

Rack::RACK_HIJACK = T.let(T.unsafe(nil), String)

Rack::RACK_HIJACK_IO = T.let(T.unsafe(nil), String)

Rack::RACK_INPUT = T.let(T.unsafe(nil), String)

Rack::RACK_IS_HIJACK = T.let(T.unsafe(nil), String)

Rack::RACK_LOGGER = T.let(T.unsafe(nil), String)

Rack::RACK_METHODOVERRIDE_ORIGINAL_METHOD = T.let(T.unsafe(nil), String)

Rack::RACK_MULTIPART_BUFFER_SIZE = T.let(T.unsafe(nil), String)

Rack::RACK_MULTIPART_TEMPFILE_FACTORY = T.let(T.unsafe(nil), String)

Rack::RACK_MULTIPROCESS = T.let(T.unsafe(nil), String)

Rack::RACK_MULTITHREAD = T.let(T.unsafe(nil), String)

Rack::RACK_RECURSIVE_INCLUDE = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_COOKIE_HASH = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_COOKIE_STRING = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_FORM_HASH = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_FORM_INPUT = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_FORM_VARS = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_QUERY_HASH = T.let(T.unsafe(nil), String)

Rack::RACK_REQUEST_QUERY_STRING = T.let(T.unsafe(nil), String)

Rack::RACK_RUNONCE = T.let(T.unsafe(nil), String)

Rack::RACK_SESSION = T.let(T.unsafe(nil), String)

Rack::RACK_SESSION_OPTIONS = T.let(T.unsafe(nil), String)

Rack::RACK_SESSION_UNPACKED_COOKIE_DATA = T.let(T.unsafe(nil), String)

Rack::RACK_SHOWSTATUS_DETAIL = T.let(T.unsafe(nil), String)

Rack::RACK_TEMPFILES = T.let(T.unsafe(nil), String)

Rack::RACK_URL_SCHEME = T.let(T.unsafe(nil), String)

Rack::RACK_VERSION = T.let(T.unsafe(nil), String)

Rack::RELEASE = T.let(T.unsafe(nil), String)

Rack::REQUEST_METHOD = T.let(T.unsafe(nil), String)

Rack::REQUEST_PATH = T.let(T.unsafe(nil), String)

Rack::SCRIPT_NAME = T.let(T.unsafe(nil), String)

Rack::SERVER_NAME = T.let(T.unsafe(nil), String)

Rack::SERVER_PORT = T.let(T.unsafe(nil), String)

Rack::SERVER_PROTOCOL = T.let(T.unsafe(nil), String)

Rack::SET_COOKIE = T.let(T.unsafe(nil), String)

Rack::TRACE = T.let(T.unsafe(nil), String)

Rack::TRANSFER_ENCODING = T.let(T.unsafe(nil), String)

Rack::UNLINK = T.let(T.unsafe(nil), String)

Rack::VERSION = T.let(T.unsafe(nil), Array)
