version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '12:00'
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - connorshea
  ignore:
  - dependency-name: aws-partitions
    versions: [">= 0"]
  - dependency-name: aws-sdk-core
    versions: [">= 0"]
  - dependency-name: aws-sdk-kms
    versions: [">= 0"]
  - dependency-name: aws-sdk-s3
    versions: [">= 0"]
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: '12:00'
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - connorshea
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '12:00'
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - connorshea
  ignore:
  - dependency-name: "@types/lodash"
    versions: [">= 0"]
  - dependency-name: "@types/node"
    versions: [">= 0"]
  - dependency-name: "@sentry/browser"
    versions: [">= 0"]
  - dependency-name: "@sentry/integrations"
    versions: [">= 0"]
  - dependency-name: "vue"
    versions: [">= 0"]
    update-types: ["version-update:semver-major"]
