[build]
builder = "railpack"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
preDeployCommand = "bundle exec rails db:prepare"
healthcheckPath = "/up"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 4
