# typed: true
# frozen_string_literal: true

require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "active_job/railtie"
require "active_model/railtie"
require "active_record"
require "active_record/railtie"
require "active_storage/engine"
require "active_storage_validations/matchers"
require "active_support/core_ext/integer/time"
require "addressable/template"
require "aws-sdk-s3"
require "bootsnap/setup"
require "bundler/setup"
require "capybara/rails"
require "capybara/rspec"
require "database_cleaner"
require "devise/orm/active_record"
require "json"
require "mkmf"
require "net/http"
require "open-uri"
require "paper_trail/frameworks/rspec"
require "pundit/matchers"
require "pundit/rspec"
require "rails"
require "rails/all"
require "rails/test_unit/railtie"
require "rspec/expectations"
require "rspec/rails"
require "rubocop"
require "rubocop-performance"
require "rubocop-rails"
require "rubocop-rspec"
require "ruby-progressbar"
require "selenium/webdriver"
require "set"
require "simplecov"
require "sparql"
require "sparql/client"
require "webdrivers"
require "webmock/rspec"

# Custom:
require "paper_trail/frameworks/active_record"
