class Relationship < ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[Relationship, Relationship::ActiveRecord_Relation]

  attr_accessor id (): Integer
  def id_changed?: () -> bool
  def id_change: () -> [Integer?, Integer?]
  def id_will_change!: () -> void
  def id_was: () -> Integer?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[Integer?]?
  def id_previously_was: () -> Integer?
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor follower_id (): Integer
  def follower_id_changed?: () -> bool
  def follower_id_change: () -> [Integer?, Integer?]
  def follower_id_will_change!: () -> void
  def follower_id_was: () -> Integer?
  def follower_id_previously_changed?: () -> bool
  def follower_id_previous_change: () -> Array[Integer?]?
  def follower_id_previously_was: () -> Integer?
  def restore_follower_id!: () -> void
  def clear_follower_id_change: () -> void

  attr_accessor followed_id (): Integer
  def followed_id_changed?: () -> bool
  def followed_id_change: () -> [Integer?, Integer?]
  def followed_id_will_change!: () -> void
  def followed_id_was: () -> Integer?
  def followed_id_previously_changed?: () -> bool
  def followed_id_previous_change: () -> Array[Integer?]?
  def followed_id_previously_was: () -> Integer?
  def restore_followed_id!: () -> void
  def clear_followed_id_change: () -> void

  attr_accessor created_at (): ActiveSupport::TimeWithZone
  def created_at_changed?: () -> bool
  def created_at_change: () -> [ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone?]
  def created_at_will_change!: () -> void
  def created_at_was: () -> ActiveSupport::TimeWithZone?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at (): ActiveSupport::TimeWithZone
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone?]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  def events: () -> Event::ActiveRecord_Associations_CollectionProxy
  def events=: (Event::ActiveRecord_Associations_CollectionProxy | Array[Event]) -> (Event::ActiveRecord_Associations_CollectionProxy | Array[Event])
  def event_ids: () -> Array[Integer]
  def event_ids=: (Array[Integer]) -> Array[Integer]

  def follower: () -> User
  def follower=: (User?) -> User?
  def build_follower: (untyped) -> User
  def create_follower: (untyped) -> User
  def create_follower!: (untyped) -> User
  def reload_follower: () -> User?
  def followed: () -> User
  def followed=: (User?) -> User?
  def build_followed: (untyped) -> User
  def create_followed: (untyped) -> User
  def create_followed!: (untyped) -> User
  def reload_followed: () -> User?



end

class Relationship::ActiveRecord_Relation < ActiveRecord::Relation
  include _ActiveRecord_Relation[Relationship]
  include Enumerable[Relationship]


end

class Relationship::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
