interface _RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def rails_mailers_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def new_user_session_path: (*untyped) -> String
  def user_session_path: (*untyped) -> String
  def destroy_user_session_path: (*untyped) -> String
  def new_user_password_path: (*untyped) -> String
  def edit_user_password_path: (*untyped) -> String
  def user_password_path: (*untyped) -> String
  def cancel_user_registration_path: (*untyped) -> String
  def new_user_registration_path: (*untyped) -> String
  def edit_user_registration_path: (*untyped) -> String
  def user_registration_path: (*untyped) -> String
  def new_user_confirmation_path: (*untyped) -> String
  def user_confirmation_path: (*untyped) -> String
  def home_index_path: (*untyped) -> String
  def search_games_path: (*untyped) -> String
  def add_game_to_library_game_path: (*untyped) -> String
  def remove_game_from_library_game_path: (*untyped) -> String
  def remove_cover_game_path: (*untyped) -> String
  def favorite_game_path: (*untyped) -> String
  def unfavorite_game_path: (*untyped) -> String
  def favorited_game_path: (*untyped) -> String
  def merge_game_path: (*untyped) -> String
  def add_to_wikidata_blocklist_game_path: (*untyped) -> String
  def games_path: (*untyped) -> String
  def new_game_path: (*untyped) -> String
  def edit_game_path: (*untyped) -> String
  def game_path: (*untyped) -> String
  def bulk_update_game_purchases_path: (*untyped) -> String
  def game_purchases_path: (*untyped) -> String
  def game_purchase_path: (*untyped) -> String
  def users_path: (*untyped) -> String
  def search_users_path: (*untyped) -> String
  def user_path: (*untyped) -> String
  def statistics_user_path: (*untyped) -> String
  def activity_user_path: (*untyped) -> String
  def compare_users_path: (*untyped) -> String
  def update_role_user_path: (*untyped) -> String
  def remove_avatar_user_path: (*untyped) -> String
  def connect_steam_user_path: (*untyped) -> String
  def disconnect_steam_user_path: (*untyped) -> String
  def steam_import_user_path: (*untyped) -> String
  def reset_game_library_user_path: (*untyped) -> String
  def favorites_user_path: (*untyped) -> String
  def following_user_path: (*untyped) -> String
  def followers_user_path: (*untyped) -> String
  def user_follow_path: (*untyped) -> String
  def user_unfollow_path: (*untyped) -> String
  def reset_token_users_path: (*untyped) -> String
  def ban_user_path: (*untyped) -> String
  def unban_user_path: (*untyped) -> String
  def new_user_path: (*untyped) -> String
  def edit_user_path: (*untyped) -> String
  def activity_path: (*untyped) -> String
  def activity_following_path: (*untyped) -> String
  def admin_path: (*untyped) -> String
  def admin_wikidata_blocklist_path: (*untyped) -> String
  def admin_remove_from_wikidata_blocklist_path: (*untyped) -> String
  def admin_new_steam_blocklist_path: (*untyped) -> String
  def admin_steam_blocklist_path: (*untyped) -> String
  def admin_add_to_steam_blocklist_path: (*untyped) -> String
  def admin_remove_from_steam_blocklist_path: (*untyped) -> String
  def admin_games_without_wikidata_ids_path: (*untyped) -> String
  def event_path: (*untyped) -> String
  def search_platforms_path: (*untyped) -> String
  def platforms_path: (*untyped) -> String
  def new_platform_path: (*untyped) -> String
  def edit_platform_path: (*untyped) -> String
  def platform_path: (*untyped) -> String
  def search_engines_path: (*untyped) -> String
  def engines_path: (*untyped) -> String
  def new_engine_path: (*untyped) -> String
  def edit_engine_path: (*untyped) -> String
  def engine_path: (*untyped) -> String
  def search_genres_path: (*untyped) -> String
  def genres_path: (*untyped) -> String
  def new_genre_path: (*untyped) -> String
  def edit_genre_path: (*untyped) -> String
  def genre_path: (*untyped) -> String
  def search_companies_path: (*untyped) -> String
  def companies_path: (*untyped) -> String
  def new_company_path: (*untyped) -> String
  def edit_company_path: (*untyped) -> String
  def company_path: (*untyped) -> String
  def search_series_index_path: (*untyped) -> String
  def series_index_path: (*untyped) -> String
  def new_series_path: (*untyped) -> String
  def edit_series_path: (*untyped) -> String
  def series_path: (*untyped) -> String
  def search_stores_path: (*untyped) -> String
  def stores_path: (*untyped) -> String
  def new_store_path: (*untyped) -> String
  def edit_store_path: (*untyped) -> String
  def store_path: (*untyped) -> String
  def search_path: (*untyped) -> String
  def settings_path: (*untyped) -> String
  def settings_account_path: (*untyped) -> String
  def settings_import_path: (*untyped) -> String
  def settings_export_path: (*untyped) -> String
  def settings_export_as_json_path: (*untyped) -> String
  def settings_api_token_path: (*untyped) -> String
  def native_oauth_authorization_path: (*untyped) -> String
  def oauth_authorization_path: (*untyped) -> String
  def oauth_token_path: (*untyped) -> String
  def oauth_revoke_path: (*untyped) -> String
  def oauth_introspect_path: (*untyped) -> String
  def oauth_applications_path: (*untyped) -> String
  def new_oauth_application_path: (*untyped) -> String
  def edit_oauth_application_path: (*untyped) -> String
  def oauth_application_path: (*untyped) -> String
  def oauth_authorized_applications_path: (*untyped) -> String
  def oauth_authorized_application_path: (*untyped) -> String
  def oauth_token_info_path: (*untyped) -> String
  def about_path: (*untyped) -> String
  def graphiql_path: (*untyped) -> String
  def graphql_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_service_blob_proxy_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_blob_representation_proxy_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_storage_proxy_path: (*untyped) -> String
  def rails_storage_redirect_path: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def root_url: (*untyped) -> String
  def new_user_session_url: (*untyped) -> String
  def user_session_url: (*untyped) -> String
  def destroy_user_session_url: (*untyped) -> String
  def new_user_password_url: (*untyped) -> String
  def edit_user_password_url: (*untyped) -> String
  def user_password_url: (*untyped) -> String
  def cancel_user_registration_url: (*untyped) -> String
  def new_user_registration_url: (*untyped) -> String
  def edit_user_registration_url: (*untyped) -> String
  def user_registration_url: (*untyped) -> String
  def new_user_confirmation_url: (*untyped) -> String
  def user_confirmation_url: (*untyped) -> String
  def home_index_url: (*untyped) -> String
  def search_games_url: (*untyped) -> String
  def add_game_to_library_game_url: (*untyped) -> String
  def remove_game_from_library_game_url: (*untyped) -> String
  def remove_cover_game_url: (*untyped) -> String
  def favorite_game_url: (*untyped) -> String
  def unfavorite_game_url: (*untyped) -> String
  def favorited_game_url: (*untyped) -> String
  def merge_game_url: (*untyped) -> String
  def add_to_wikidata_blocklist_game_url: (*untyped) -> String
  def games_url: (*untyped) -> String
  def new_game_url: (*untyped) -> String
  def edit_game_url: (*untyped) -> String
  def game_url: (*untyped) -> String
  def bulk_update_game_purchases_url: (*untyped) -> String
  def game_purchases_url: (*untyped) -> String
  def game_purchase_url: (*untyped) -> String
  def users_url: (*untyped) -> String
  def search_users_url: (*untyped) -> String
  def user_url: (*untyped) -> String
  def statistics_user_url: (*untyped) -> String
  def activity_user_url: (*untyped) -> String
  def compare_users_url: (*untyped) -> String
  def update_role_user_url: (*untyped) -> String
  def remove_avatar_user_url: (*untyped) -> String
  def connect_steam_user_url: (*untyped) -> String
  def disconnect_steam_user_url: (*untyped) -> String
  def steam_import_user_url: (*untyped) -> String
  def reset_game_library_user_url: (*untyped) -> String
  def favorites_user_url: (*untyped) -> String
  def following_user_url: (*untyped) -> String
  def followers_user_url: (*untyped) -> String
  def user_follow_url: (*untyped) -> String
  def user_unfollow_url: (*untyped) -> String
  def reset_token_users_url: (*untyped) -> String
  def ban_user_url: (*untyped) -> String
  def unban_user_url: (*untyped) -> String
  def new_user_url: (*untyped) -> String
  def edit_user_url: (*untyped) -> String
  def activity_url: (*untyped) -> String
  def activity_following_url: (*untyped) -> String
  def admin_url: (*untyped) -> String
  def admin_wikidata_blocklist_url: (*untyped) -> String
  def admin_remove_from_wikidata_blocklist_url: (*untyped) -> String
  def admin_new_steam_blocklist_url: (*untyped) -> String
  def admin_steam_blocklist_url: (*untyped) -> String
  def admin_add_to_steam_blocklist_url: (*untyped) -> String
  def admin_remove_from_steam_blocklist_url: (*untyped) -> String
  def admin_games_without_wikidata_ids_url: (*untyped) -> String
  def event_url: (*untyped) -> String
  def search_platforms_url: (*untyped) -> String
  def platforms_url: (*untyped) -> String
  def new_platform_url: (*untyped) -> String
  def edit_platform_url: (*untyped) -> String
  def platform_url: (*untyped) -> String
  def search_engines_url: (*untyped) -> String
  def engines_url: (*untyped) -> String
  def new_engine_url: (*untyped) -> String
  def edit_engine_url: (*untyped) -> String
  def engine_url: (*untyped) -> String
  def search_genres_url: (*untyped) -> String
  def genres_url: (*untyped) -> String
  def new_genre_url: (*untyped) -> String
  def edit_genre_url: (*untyped) -> String
  def genre_url: (*untyped) -> String
  def search_companies_url: (*untyped) -> String
  def companies_url: (*untyped) -> String
  def new_company_url: (*untyped) -> String
  def edit_company_url: (*untyped) -> String
  def company_url: (*untyped) -> String
  def search_series_index_url: (*untyped) -> String
  def series_index_url: (*untyped) -> String
  def new_series_url: (*untyped) -> String
  def edit_series_url: (*untyped) -> String
  def series_url: (*untyped) -> String
  def search_stores_url: (*untyped) -> String
  def stores_url: (*untyped) -> String
  def new_store_url: (*untyped) -> String
  def edit_store_url: (*untyped) -> String
  def store_url: (*untyped) -> String
  def search_url: (*untyped) -> String
  def settings_url: (*untyped) -> String
  def settings_account_url: (*untyped) -> String
  def settings_import_url: (*untyped) -> String
  def settings_export_url: (*untyped) -> String
  def settings_export_as_json_url: (*untyped) -> String
  def settings_api_token_url: (*untyped) -> String
  def native_oauth_authorization_url: (*untyped) -> String
  def oauth_authorization_url: (*untyped) -> String
  def oauth_token_url: (*untyped) -> String
  def oauth_revoke_url: (*untyped) -> String
  def oauth_introspect_url: (*untyped) -> String
  def oauth_applications_url: (*untyped) -> String
  def new_oauth_application_url: (*untyped) -> String
  def edit_oauth_application_url: (*untyped) -> String
  def oauth_application_url: (*untyped) -> String
  def oauth_authorized_applications_url: (*untyped) -> String
  def oauth_authorized_application_url: (*untyped) -> String
  def oauth_token_info_url: (*untyped) -> String
  def about_url: (*untyped) -> String
  def graphiql_url: (*untyped) -> String
  def graphql_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_service_blob_proxy_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_blob_representation_proxy_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
  def rails_storage_proxy_url: (*untyped) -> String
  def rails_storage_redirect_url: (*untyped) -> String
end
