# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::MakeMakefile; end
module DeleteInvalidEventsRecords::Event; end
module MoveGamePurchaseEvents::Event; end
module PaperTrail::Model; end
module PaperTrail::VersionConcern; end
module RenameGamePurchaseEventsToEvents::Event; end
