# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ::Colorize::ClassMethods; end
module ::Colorize::InstanceMethods; end
module ::MakeMakefile; end
module ::Vips::Image; end
module RDoc::Task; end
module T::Private::Methods::Signature; end
