# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:helpers to regenerate.
# typed: strong

module ApplicationHelper
  include Kernel
end

module GamesHelper
  include Kernel
end

module GenresHelper
  include Kernel
end

module HomeHelper
  include Kernel
end

module PlatformsHelper
  include Kernel
end

module SettingsHelper
  include Kernel
end

module DeviseHelper
  include Kernel
end

