name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@0cb964fd540e0a24c900370abf38a33466142735 # v1.305.0
        with:
          ruby-version: "3.4.9"
          bundler-cache: true

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          package_json_file: frontend/package.json

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - run: pnpm --dir frontend install --frozen-lockfile

      - run: pnpm --dir frontend run lint --fix
      - run: pnpm --dir frontend run fmt

      - run: bundle exec rubocop --autocorrect

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
