name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: "3.4.9"
          bundler-cache: true

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1
        with:
          package_json_file: frontend/package.json

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - run: pnpm --dir frontend install --frozen-lockfile

      - run: pnpm --dir frontend run lint --fix
      - run: pnpm --dir frontend run fmt

      - run: bundle exec rubocop --autocorrect

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
