name: Copilot Setup Steps
# This workflow is used by GitHub Copilot to set up the environment
# for the coding agent functionality.
# See docs for more info:
# https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment
# Without this, Copilot is very slow and kinda dumb.

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: vglist_development
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: development
      BUNDLER_VERSION: '2.7.1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.260.0
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Setup database
        run: |
          bundle exec rails db:setup

      - name: Validate setup
        run: |
          echo "Testing database connectivity..."
          bundle exec rails runner \
            "puts 'Database connection: OK'; \
            puts 'User count: ' + User.count.to_s"
